### ISSUE TITLE
Problem with forced subtitle flag on mpv

### ISSUE THREAD

**Issue by xSlysoft** [Kaleido-subs/FSN-Heavens-Feel#2]
It's possible that this issue is from my own mpv config, but I've never run into it before so I thought I might bring it up to look for a solution.

With the default stock settings, the subtitle track in mpv always default to the signs track, even though the full subtitles are flagged as default and forced in the header. Removing the forced flag element with mkvtoolnix header editor is all it takes to cause the full subtitle track to be the automatic default as intended. I have tried adding `sub-forced-only` and `subs-with-matching-audio` settings to mpv.conf and playing around with different configurations, but the only thing which solved my problem was removing the forced flag in mkvtoolnix.

Is there some kind of setting that I am missing with mpv that is causing it to avoid the forced subtitle track? Normally the forced flag doesn't do anything for me and the player just follows the default flagged track. Also, the Japanese audio track is flagged default and forced but in this case the player defaults to Japanese as intended without any manipulation.

**Comment by petzku** [comment]
This is an honest mistake that happened when muxing—the forced tag should indeed be on the "Signs & Songs" track, not the "Full dialogue" one. Should be fixed in an eventual v2 release, once dub BDs come out for the third movie.
